/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.sql.*;
import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

/**
 *
 * @author Raul Gomez
 */
public class Administrador extends javax.swing.JFrame {

    String user, nombre_usuario;
    public static int sesion_usuario;

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        user = Login.user;
        sesion_usuario = 1;
        
        setSize(650, 430);
        setResizable(false);
        setTitle("Administrador - Sesion de " + user);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon("src/images/BlancoMetalico.png");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select nombre_usuario from usuarios where username = '"+ user + "'");
            
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                nombre_usuario = rs.getString("nombre_usuario");
                jLabel_NombreUsuario.setText(nombre_usuario);
            }
            
        } catch (Exception e) {
            System.err.println("Error en coneccion desde la interface administrador");
            
        }
    }

    @Override
    public Image getIconImage() {
        Image redValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/iconN.png"));
        return redValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_NombreUsuario = new javax.swing.JLabel();
        jLabel_SaludoUsuario = new javax.swing.JLabel();
        jButton_RegistrarUsuario = new javax.swing.JButton();
        jButton_GestionarUsuarios = new javax.swing.JButton();
        jButton_Creatividad = new javax.swing.JButton();
        jButton_Capturista = new javax.swing.JButton();
        jButton_Tecnico = new javax.swing.JButton();
        jButton_Acerca_de = new javax.swing.JButton();
        jLabel_RegistrarUsuario = new javax.swing.JLabel();
        jLabel_GestionarUsuario = new javax.swing.JLabel();
        jLabel_Creatividad = new javax.swing.JLabel();
        jLabel_Capturista = new javax.swing.JLabel();
        jLabel_Tecnico = new javax.swing.JLabel();
        jLabel_AcercaDe = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_NombreUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_NombreUsuario.setForeground(new java.awt.Color(102, 102, 255));
        getContentPane().add(jLabel_NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 80, 20));

        jLabel_SaludoUsuario.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel_SaludoUsuario.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_SaludoUsuario.setText("Hola");
        getContentPane().add(jLabel_SaludoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jButton_RegistrarUsuario.setBackground(new java.awt.Color(51, 153, 255));
        jButton_RegistrarUsuario.setForeground(new java.awt.Color(255, 153, 51));
        jButton_RegistrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man_User_2_6_mm_ancho.png"))); // NOI18N
        jButton_RegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_RegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 140, 100));

        jButton_GestionarUsuarios.setBackground(new java.awt.Color(51, 153, 255));
        jButton_GestionarUsuarios.setForeground(new java.awt.Color(255, 153, 51));
        jButton_GestionarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/woman&men_User_6mm_ancho.png"))); // NOI18N
        jButton_GestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestionarUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_GestionarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 140, 100));

        jButton_Creatividad.setBackground(new java.awt.Color(51, 153, 255));
        jButton_Creatividad.setForeground(new java.awt.Color(255, 153, 51));
        jButton_Creatividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Electronica.png"))); // NOI18N
        getContentPane().add(jButton_Creatividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 140, 100));

        jButton_Capturista.setBackground(new java.awt.Color(51, 153, 255));
        jButton_Capturista.setForeground(new java.awt.Color(255, 153, 51));
        jButton_Capturista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/woman_User_2.png"))); // NOI18N
        getContentPane().add(jButton_Capturista, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 140, 100));

        jButton_Tecnico.setBackground(new java.awt.Color(51, 153, 255));
        jButton_Tecnico.setForeground(new java.awt.Color(255, 153, 51));
        jButton_Tecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man_User_1_6mm_ancho.png"))); // NOI18N
        getContentPane().add(jButton_Tecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 140, 100));

        jButton_Acerca_de.setBackground(new java.awt.Color(51, 153, 255));
        jButton_Acerca_de.setForeground(new java.awt.Color(255, 153, 51));
        jButton_Acerca_de.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DesarrolloApps_6mm_ancho.png"))); // NOI18N
        getContentPane().add(jButton_Acerca_de, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 140, 100));

        jLabel_RegistrarUsuario.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel_RegistrarUsuario.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_RegistrarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_RegistrarUsuario.setText("Registrar Usuario");
        jLabel_RegistrarUsuario.setRequestFocusEnabled(false);
        getContentPane().add(jLabel_RegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 175, 140, -1));

        jLabel_GestionarUsuario.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel_GestionarUsuario.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_GestionarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_GestionarUsuario.setText("Gestionar Usuarios");
        getContentPane().add(jLabel_GestionarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 175, 150, -1));

        jLabel_Creatividad.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel_Creatividad.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Creatividad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Creatividad.setText("Insumos");
        getContentPane().add(jLabel_Creatividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 175, 140, -1));

        jLabel_Capturista.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel_Capturista.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Capturista.setText("Panel Vista Capturista");
        getContentPane().add(jLabel_Capturista, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 345, 170, -1));

        jLabel_Tecnico.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel_Tecnico.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Tecnico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Tecnico.setText("Panel Vista Tecnico");
        getContentPane().add(jLabel_Tecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 345, 170, -1));

        jLabel_AcercaDe.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        jLabel_AcercaDe.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_AcercaDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_AcercaDe.setText("Acerca de ...");
        getContentPane().add(jLabel_AcercaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 345, 140, -1));

        jLabel1.setText("Creado por Raúl Gómez");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 380, -1, -1));

        jLabel_Wallpaper.setForeground(new java.awt.Color(153, 153, 255));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarUsuarioActionPerformed
        
        RegistrarUsuario registrarUsuario = new RegistrarUsuario();
        registrarUsuario.setVisible(true);
    }//GEN-LAST:event_jButton_RegistrarUsuarioActionPerformed

    private void jButton_GestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestionarUsuariosActionPerformed
        
        GestionarUsuarios gestionarUsuarios = new GestionarUsuarios();
        gestionarUsuarios.setVisible(true);
        
    }//GEN-LAST:event_jButton_GestionarUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Acerca_de;
    private javax.swing.JButton jButton_Capturista;
    private javax.swing.JButton jButton_Creatividad;
    private javax.swing.JButton jButton_GestionarUsuarios;
    private javax.swing.JButton jButton_RegistrarUsuario;
    private javax.swing.JButton jButton_Tecnico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_AcercaDe;
    private javax.swing.JLabel jLabel_Capturista;
    private javax.swing.JLabel jLabel_Creatividad;
    private javax.swing.JLabel jLabel_GestionarUsuario;
    private javax.swing.JLabel jLabel_NombreUsuario;
    private javax.swing.JLabel jLabel_RegistrarUsuario;
    private javax.swing.JLabel jLabel_SaludoUsuario;
    private javax.swing.JLabel jLabel_Tecnico;
    private javax.swing.JLabel jLabel_Wallpaper;
    // End of variables declaration//GEN-END:variables
}
